config/routes.rb
Rails.application.routes.draw do
  
  resources :interviews
  root "interviews#index"
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  resources :users , only: [:new, :create]
  resources :sessions , only: [:new, :create, :destroy]
end

app/views/partials/_calender.html.erb
    <h1 class="title text-center mb-3">
        <span style="display:none" id="monthspan"><%= @details[:month] %></span>
        <span><%= Date::MONTHNAMES[@details[:month]] %></span>
        <span id="yearspan"><%= @details[:year] %></span>
    </h1>
    <div class="calendar" data-toggle="calendar">
        <div class="row">
            <div class="col-xs-12 calendar-day calendar-no-current-month"></div>
            <div class="col-xs-12 calendar-day calendar-no-current-month"></div>

            <% for day in 1..33 do %>
                <% if day>@details[:days] %>
                    <div class="col-xs-12 calendar-day calendar-no-current-month"></div>
                <% elsif (day+1).modulo(7) === 0 %>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 calendar-day ">
                            <span id="day" style="float:right" class="mr-2 mt-1"><h3><%= day %></h3></span>
                            <%= link_to  "Events", interviews_path(month: @details[:month], year: @details[:year], day: "#{day}"), id:"see-events" %>
                            <a id="openModal" data-toggle="modal" data-target="#myModal"><h2>+</h2></a>
                        </div>
                <% else %>
                    <div class="col-xs-12 calendar-day ">
                        <span id="day" style="float:right" class="mr-2 mt-1"><h3><%= day %></h3></span>
                        <%= link_to  "events", interviews_path(month: @details[:month], year: @details[:year], day: "#{day}"), id:"see-events" %>
                        <a id="openModal" data-toggle="modal" data-target="#myModal"><h2>+</h2></a>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>

app/views/partials/_header_form.html.erb
<p id="error-message"></p>
<form id="indexform" action="/interviews" class="form-inline">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                Enter month: <input id="month" name="month" class="form-control" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                Enter year: <input id="year" name="year" class="form-control" />
            </div>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary" id="submit">submit</button>
        </div>
    </div>
</form>

app/views/partials/_interviews.html.erb
<ul class="list-group">
    <% interviews.each do |interview| %>
    <li class="list-group-item">
        <% if edit_interview && interview.id == edit_interview.id %>
            <%= form_tag(interview_path, method: :put ) do %>
                <div class="form-group">
                    <% if edit_interview.errors[:title].any? %><p id="error-message"><%= edit_interview.errors[:title][0] %></p><% end %>
                    <label>Title </label><br />
                    <%= text_field_tag :title, edit_interview.title %>
                </div>

                 <div class="form-group">
                    <label>Select date for the interview </label><br />
                    <%= date_field_tag :date, edit_interview.starttime.strftime("%Y-%m-%d") %>
                </div>

                <div class="form-group">
                    <% if edit_interview.errors[:starttime].any? %><p id="error-message"><%= edit_interview.errors[:starttime][0] %></p><% end %>
                    <label>Select start time for the interview </label><br />
                    <%= time_field_tag :starttime, edit_interview.starttime.strftime("%H:%M"), :ignore_date => true %>
                </div>

                <div class="form-group">
                    <% if edit_interview.errors[:endtime].any? %><p id="error-message"><%= edit_interview.errors[:endtime][0] %></p><% end %>
                    <label>Select end time for the interview </label><br />
                    <%= time_field_tag :endtime, edit_interview.endtime.strftime("%H:%M"), :ignore_date => true %>
                </div>
                

                <div class="form-group">
                    <% if edit_interview.errors[:participants].any? %><p id="error-message"><%= edit_interview.errors[:participants][0] %></p><% end %>
                    <label> Add Participants</label><br />
                    <select class="custom-select form-control" name="participants[]" multiple>
                        <%= User.all.each do |participant| %>
                        <option value="<%= participant.id %>"><%= participant.firstname.concat(" ").concat(participant.lastname) %></option>
                        <% end %>
                    </select>
                    <small id="optionHelp" class="form-text text-muted">Hold ctrl Key to add multiple participants</small>
                </div>
                <%= submit_tag "Schedule" , class: "btn btn-primary" %>
            <% end %>

        <% else %>
        <% if interview.interviewer_id == current_user.id %>
            <%= link_to  "Edit", edit_interview_path(interview.id, month: details[:month], year: details[:year], day: interview.starttime.day ),  style: "float:right" %>
        <% end %>
        <%= link_to  "Back", interviews_path(month: details[:month], year: details[:year]) %>
        <h4 class="text-center"><%= interview.title %></h4>
        <h5 class="text-muted"><%= interview.starttime.to_formatted_s(:long_ordinal) %> | <%= interview.endtime.to_formatted_s(:long_ordinal) %></h5> 
        <h5> Organizer - <%= User.find(interview.interviewer_id).firstname %> </h5>
        <h5> Participants </h5>
        <ul class="list-inline">
            <% interview.participants.each do |participant| %>
            <li class="text-muted"><%= participant.firstname + " " + participant.lastname %></li>
            <% end %>
        </ul>
        <h5> Resumes </h5>
        <% if interview.resumes.attached? %>
            <% interview.resumes.each do |resume| %>
                <%= link_to "resume#{(0...8).map { (65 + rand(26)).chr }.join}", rails_blob_path(resume, disposition: 'preview') %><br />
            <% end %>
        <% end %>
        <br/>
        <% if interview.interviewer_id == current_user.id %>
            <%= link_to  "Delete", interview_path(interview.id, month: details[:month], year: details[:year], day: interview.starttime.day ), method: :delete %>
        <% end %>
        <% end %>
    </li>
    <% end %>
</ul>

app/views/partials/_modal.html.erb
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create a new interview </h4>
            </div>
            <div class="modal-body">
                <%= form_tag interviews_path , multipart: true do %>
                <%= hidden_field_tag :day %>
                <%= hidden_field_tag :month %>
                <%= hidden_field_tag :year %>

                <div class="form-group">
                    <label>Title </label><br />
                    <%= text_field_tag :title%>
                </div>

                <div class="form-group">
                    <label>Select start time for the interview </label><br />
                    <%= time_field_tag :starttime, :ignore_date => true %>
                </div>

                <div class="form-group">
                    <label>Select end time for the interview </label><br />
                    <%= time_field_tag :endtime, :ignore_date => true %>
                </div>

                <div class="form-group">

                    <label> Add Participants</label><br />
                    <select class="custom-select form-control" name="participants[]" multiple>
                        <%= User.where.not(id: current_user.id).each do |participant| %>
                        <option value="<%= participant.id %>"><%= participant.firstname.concat(" ").concat(participant.lastname) %></option>
                        <% end %>
                    </select>
                    <small id="optionHelp" class="form-text text-muted">Hold ctrl Key to add multiple participants</small>
                </div>

                <div class="form-group">
                    <label> Add Resumes </label><br />
                    <%= file_field_tag :resumes, name: 'resumes[]', multiple: true, class: 'btn btn-primary', required: true %>
                </div>

                <%= submit_tag "Schedule" , class: "btn btn-primary" %>
                <% end %>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>