config/routes.rb
Rails.application.routes.draw do
  
  resources :interviews
  root "interviews#index"
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  resources :users , only: [:new, :create]
  resources :sessions , only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  #a user will have a secure password (maintained through bcrypt)
  has_secure_password
  #a user has many interviews that he has created, identified by foreign_key interviewer_id
  has_many :interviews_created, :foreign_key => "interviewer_id", :class_name => "Interview"
  #a user can also participate in many interviews
  has_and_belongs_to_many :interviews_participated, :class_name => "Interview"

  #validations added
  validates :firstname, presence: true, length: { minimum: 2 }
  validates :lastname, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/users_controller.rb
#user controller manages the users of the application
class UsersController < ApplicationController
    #before the show action, we need to make sure that the user is logged in first, the authorized helper is defined in application_controller.rb
    before_action :authorized, only: [:show]

    #displays the registration form
    def new
        #passes an empty user object
        @user = User.new
    end

    #creates a new user
    def create
        #creates a new user from the user params
        @user = User.create(user_params)
        if @user.save
            #if the user is saved successfully, redirect to the timeline view
            redirect_to root_path
        else
            #otherwise render another form, and display the validation errors
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:firstname,:lastname, :email, :password, :password_confirmation)
    end

end

app/views/users/new.html.erb
<div class="container">
    <!-- user registration form -->
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Create Account</h4>
            <p class="text-center">Get started with your free account</p>
            <%= form_for @user do |f| %>
            <% if @user.errors[:firstname].any? %><span id="error"><%= @user.errors[:firstname][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.text_field :firstname , class: "form-control mb-2 mr-sm-2" ,placeholder: "firstname" %>
            </div>

            <% if @user.errors[:lastname].any? %><span id="error"><%= @user.errors[:lastname][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.text_field :lastname , class: "form-control mb-2 mr-sm-2" ,placeholder: "lastname" %>
            </div>

            <% if @user.errors[:email].any? %><span id="error"><%= @user.errors[:email][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.email_field :email , class: "form-control mb-2 mr-sm-2" ,placeholder: "email" %>
            </div>
            <% if @user.errors[:password].any? %><span id="error"><%= @user.errors[:password][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.password_field :password , class: "form-control mb-2 mr-sm-2" ,placeholder: "password" %>
            </div>
            <% if @user.errors[:password_confirmation].any? %><span id="error"><%= @user.errors[:password_confirmation][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.password_field :password_confirmation , class: "form-control mb-2 mr-sm-2" ,placeholder: "confirm password" %>
            </div>
            <div class="form-group">
                <%= f.submit  "Create Account", class: "btn btn-primary" %>
            </div>
            <% end %>
            <p class="text-center">Have an account? <%= link_to  "Log In", new_session_path %></p>
        </article>
    </div> <!-- card.// -->

</div>